# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
import numpy as np
a1=np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
a2=np.reshape(a1,(2,5))
a2


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [29]:
a1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
a2=np.array ([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((a1,a2))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [30]:
a1=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
a2=np.array ([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((a1,a2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [54]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b=a.flatten()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [57]:
a = np.array([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]])
a.ndim

3

In [59]:
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [67]:
a = np.arange(15)
a.reshape((5,3))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [70]:
a1=np.empty((5,5))
np.power(a1,2)
a1

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.79098365e-307, 6.23055991e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.11260483e-306,
        1.11260755e-306, 1.42417629e-306],
       [2.22523140e-306, 1.42421160e-306, 9.34601642e-307,
        1.78021527e-306, 8.01097889e-307],
       [1.33511018e-306, 8.01089061e-307, 1.78020576e-306,
        8.34451504e-308, 2.22813476e-312]])

## Question:8

### Create 5x6 an array and find the mean?

In [82]:
a1=np.arange(30).reshape((5,6))
a1.mean()


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [86]:
a1.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [87]:
np.median(a1)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [88]:
a1.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [99]:
a1=np.arange(16).reshape((4,4))
print(a1)
np.trace(a1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [101]:
np.linalg.det(a1)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [102]:
a1=np.arange(16).reshape((4,4))
np.percentile(a1,5)

0.75

In [103]:
a1=np.arange(16).reshape((4,4))
np.percentile(a1,95)

14.25

## Question:15

### How to find if a given array has any null values?

In [106]:
a2=np.array([1,2,0,3,5,9])
np.where(a2==0,'yes','no')

array(['no', 'no', 'yes', 'no', 'no', 'no'], dtype='<U3')