In [1]:
l=range(1000000)

In [2]:
import numpy as np

In [3]:
d=np.arange(1000000)

In [7]:
%time for i in range(1,10): r= [x*2 for x in l]
    

Wall time: 2.25 s


In [8]:
%time for i in range(1,10): r= d*2

Wall time: 58.5 ms


In [11]:
x=np.zeros((4,4))

In [12]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
x=np.ones((4,4))

In [14]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((5,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.79098365e-307, 6.23055991e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.29061821e-306,
        1.78018811e-306, 1.20161322e-306],
       [1.69118108e-306, 9.34604358e-307, 1.78021527e-306,
        6.89807188e-307, 1.33511018e-306],
       [1.60220393e-306, 1.11261570e-306, 1.42410974e-306,
        1.33511969e-306, 2.18568966e-312]])

In [16]:
#list ko array mein banana
l=[1,2,3,4]

In [17]:
np.array(l)

array([1, 2, 3, 4])

In [20]:
x=np.arange(1,100,10)

In [21]:
x.shape

(10,)

In [22]:
x=np.zeros((10,10))

In [23]:
x.shape

(10, 10)

In [24]:
y=x.reshape((2,2,5,5))

In [25]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [26]:
y.dtype

dtype('float64')

In [27]:
y.ndim

4

In [28]:
a= np.random.randn((10))

In [29]:
b= np.random.randn((10))

In [30]:
a

array([-0.67626375,  0.4035679 ,  0.46042733, -1.33844489,  2.13161681,
       -1.09806804,  0.00765761, -0.8886043 , -0.11909762,  1.18731662])

In [31]:
b

array([-1.38461194, -0.59303659, -0.7581756 ,  0.01975334, -1.09295535,
        1.07947503, -1.1808392 ,  0.30927051, -0.27524276, -1.19865209])

In [32]:
#we can do a+b a*b 2*a etc
a>0

array([False,  True,  True, False,  True, False,  True, False, False,
        True])

In [33]:
a[a>0]

array([0.4035679 , 0.46042733, 2.13161681, 0.00765761, 1.18731662])

In [34]:
1/a

array([ -1.478713  ,   2.47789778,   2.17189542,  -0.74713573,
         0.46912747,  -0.91069038, 130.58901259,  -1.1253603 ,
        -8.39647339,   0.84223533])

In [35]:
#indexing and slicing
x=np.array([1,2,3,4])

In [36]:
x[2]

3

In [37]:
#bolean indexing
x[x>2]

array([3, 4])

In [38]:
#fancy indexing
x[[2,1]]

array([3, 2])

In [42]:
x=np.random.randn(3,3)

In [43]:
x

array([[-0.59196814,  0.66381747,  2.10741431],
       [ 1.05719979, -0.45118172, -0.67361521],
       [ 0.39766909,  0.7488471 , -0.04440734]])

In [46]:
x[0:2]

array([[-0.59196814,  0.66381747,  2.10741431],
       [ 1.05719979, -0.45118172, -0.67361521]])

In [48]:
x[0][2]

2.1074143063880753

In [50]:
x[1:2:2]

array([[ 1.05719979, -0.45118172, -0.67361521]])

In [53]:
x[::,0:2]

array([[-0.59196814,  0.66381747],
       [ 1.05719979, -0.45118172],
       [ 0.39766909,  0.7488471 ]])

In [54]:
x=np.ones((5,5))

In [55]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
x[1:-1,1:-1]=0

In [57]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
x=np.array([1,2,3,4])

In [59]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [60]:
np.power(x,2)

array([ 1,  4,  9, 16], dtype=int32)

In [63]:
y=[7,1,2,3]

In [64]:
np.maximum(x,y)

array([7, 2, 3, 4])

In [65]:
salary=np.array([0,-1,10000,20000])

In [67]:
np.where(salary<=0,25000,salary)

array([25000, 25000, 10000, 20000])

In [68]:
np.where(salary<=0,"ok","not ok")

array(['ok', 'ok', 'not ok', 'not ok'], dtype='<U6')

In [89]:
x=np.array([1,3,1,4])

In [90]:
x.mean()

2.25

In [91]:
x.cumsum()

array([1, 4, 5, 9], dtype=int32)

In [92]:
y=x>3

In [93]:
y.sum()

1

In [94]:
y.any()

True

In [95]:
y.all()

False

In [96]:
x.sort()

In [97]:
x

array([1, 1, 3, 4])

In [100]:
np.unique(x)

array([1, 3, 4])

In [101]:
x=[1,4,7,9]

In [102]:
y=[8,7,9]

In [103]:
np.save("testx",x)

In [105]:
loadx=np.load("testx.npy")

In [106]:
loadx

array([1, 4, 7, 9])

In [107]:
np.savez("testxy",x,y)

In [108]:
np.load("testxy.npz")

In [114]:
#linear algebra function
x=np.random.randn(3,2)
y=np.random.randn(2,3)

In [115]:
x.dot(y)

array([[-0.14172831, -0.49477455,  0.94191965],
       [ 0.09490894, -0.52448078, -2.50097563],
       [-0.11805726, -0.98472814, -0.46668785]])

In [117]:
x.transpose()

array([[ 0.41655944,  0.07684274,  0.58503495],
       [ 0.48329308, -1.60448444, -0.45439059]])

In [118]:
x.trace()

-1.1879250052934935

In [119]:
np.random.seed(7)

In [121]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])